[deps]
BlackBoxOptim = "a134a8b2-14d6-55f6-9291-3336d3ab0209"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Comrade = "99d987ce-9a1e-4df8-bc0b-1ea019aa547b"
ComradeBase = "6d8c423b-a35f-4ef1-850c-862fe21f82c4"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
Krang = "54806c32-d51a-438d-8447-e0041be2fbfb"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationGCMAES = "6f0a0517-dbc2-4a7a-8a20-99ae7f27e911"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
PairPlots = "43a3c2be-4208-490b-832a-a21dcd55d7da"
Pigeons = "0eb8d820-af6a-4919-95ae-11206f830c31"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Pyehtim = "3d61700d-6e5b-419a-8e22-9c066cf00468"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
VIDA = "4096cdfb-f084-40a3-b02d-1a2a54920cb8"
VLBIImagePriors = "b1ba175b-8447-452c-b961-7db2d6f7a029"
VLBISkyModels = "d6343c73-7174-4e0f-bb64-562643efbeca"

[compat]
julia = "1"
